### ISSUE TITLE
Better Latency In The Web Browser

### ISSUE THREAD

**Issue by Nezeky** [libcala/wavy#11]
In `webaudio/record.html` the latency is fine, but when the audio is sent to WASM and then back to JavaScript in `examples/stdweb-record/` the latency is not good enough for real-time audio applications.

**Comment by AldaronLau** [comment]
This could either be the playback or recording that has latency issues, or just the fact that it's not as direct as the JavaScript test.

**Comment by Nezeky** [comment]
The latency in wavy on WASM has been improved, so closing.
