### ISSUE TITLE
Problem with Stereo

### ISSUE THREAD

**Issue by pvitaliy84** [libcala/wavy#18]
Hello again)

in **wavy/examples/record.rs**:
```
struct State {
    buffer: Audio<Mono16>,
}
```

if change to:

```
struct State {
    buffer: Audio<Stereo16>,
}
```
problem:

```
state.buffer.extend(&mut stream);
```

_the trait bound `impl fon::Stream<Sample1<Ch16>>: fon::Stream<Sample2<Ch16>>` is not satisfied
the trait `fon::Stream<Sample2<Ch16>>` is not implemented for `impl fon::Stream<Sample1<Ch16>>`_

because:
```
let mut stream = mic.record().await;
```

**pub async fn record(&mut self) -> impl Stream<Sample1<C>> + '_**

Stereo16 = Sample2<...>

**Comment by AldaronLau** [comment]
@pvitaliy84 Thanks for finding this.  Looks like I'll have to release another version, considering that stereo audio inputs do exist and should be supported.  If you just need to convert from mono to stereo, you can record into a mono audio buffer, then call `.into()` to convert it to a stereo audio buffer.  Alternatively, or additionally, I could add an `impl` to convert a mono stream into stereo stream in the `fon` crate.

**Comment by pvitaliy84** [comment]
Thanks for your work. I very need stereo.

**Comment by AldaronLau** [comment]
@pvitaliy84 Sorry, got busy with school.  So I know what to focus on, do you need:

### A:
To record a stereo microphone (microphone with 2 channel input).

### B:
To record a mono microphone (microphone with 1 channel input), into a stereo buffer.

**Comment by AldaronLau** [comment]
@pvitaliy84 If you want to record a microphone and resample it to stereo using the stream it should work in the new version (0.7), so I'm closing this issue.  I haven't added support for 2-channel microphones yet.

**Comment by AldaronLau** [comment]
@pvitaliy84 In the newest version of wavy, both should work now.
