### ISSUE TITLE
Question: How to stream microphone output to AWS Transcribe?

### ISSUE THREAD

**Issue by thesurlydev** [libcala/wavy#41]
Can you provide any guidance on how to stream to something like AWS Transcribe instead of Speaker? I'd like to speak into a microphone and stream to AWS Transcribe for a real-time transcription.

Here's an example that reads from a wav file instead: https://github.com/awslabs/aws-sdk-rust/blob/main/examples/transcribestreaming/src/main.rs

**Comment by AldaronLau** [comment]
It would be easiest to base it off of this example:

https://github.com/libcala/wavy/blob/main/examples/record.rs

Then, once the audio is written into the `fon::Audio` buffer, call [`fon::Audio::as_f32_slice()`](https://docs.rs/fon/0.5.0/fon/struct.Audio.html#method.as_f32_slice).

After which you can iterate over the elements in the slice, calling [`f32::to_le_bytes()`](https://doc.rust-lang.org/std/primitive.f32.html#method.to_le_bytes), and push it to the `pcm: Vec<u8>` variable from your linked example.

**Comment by AldaronLau** [comment]
I'm closing this since no further explanation was requested.  Feel free to re-open if unsatisfied.
